[advisories]
unmaintained = "none"
yanked = "deny"
ignore = [
  { id = "RUSTSEC-2024-0429", reason = "Transitive dependency issue in glib, will be resolved in future updates" }
]

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MPL-2.0",
  "Unicode-DFS-2016",
  "Unicode-3.0",
  "Zlib",
  "OpenSSL",
  "BSL-1.0",
  "CC0-1.0",
  "Unlicense",
  "MIT-0",
]
confidence-threshold = 0.8

# Accept dual-licensed expressions
exceptions = [
  { name = "windows_x86_64_gnu", allow = [
    "MIT",
    "Apache-2.0",
  ] },
  { name = "android_log-sys", allow = [
    "MIT",
    "Apache-2.0",
  ] },
  { name = "windows_x86_64_gnullvm", allow = [
    "MIT",
    "Apache-2.0",
  ] },
  { name = "target-lexicon", allow = [
    "Apache-2.0 WITH LLVM-exception",
  ] },
]

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/"]
