version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username" # Replace with your actual GitHub username
    assignees:
      - "your-github-username" # Replace with your actual GitHub username
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username" # Replace with your actual GitHub username
    assignees:
      - "your-github-username" # Replace with your actual GitHub username
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username" # Replace with your actual GitHub username
    assignees:
      - "your-github-username" # Replace with your actual GitHub username
    commit-message:
      prefix: "chore"
      include: "scope"
